name: Minify JS on Push

on:
  push:
    branches: [ main ]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g uglify-js
      - run: uglifyjs script.js -o script.min.js -c -m
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автоматическая минификация JS"
          file_pattern: script.min.js
